version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
    commands:
      - echo Installing dependencies...

  pre_build:
    commands:
      - echo Preparing for build...

  build:
    commands:
      - echo Building the application...

  post_build:
    commands:
      - echo Build completed

artifacts:
  files:
    - '**/*'
